### ISSUE TITLE
runtime statistics

### ISSUE THREAD

**Issue by smilesun** [agisga/ThresholdoutAUC#1]
Is there any runtime statistics or simply an estimated number  on how long does it take for the 30 rounds to finish?  I have Intel® Xeon(R) CPU E5-2650 v2 @ 2.60GHz × 32.   I think this is comparable to the slurm cluster.  It looks like the first round has taken more than 1.5 hours without being finished yet if I have not made any mistakes.

**Comment by agisga** [comment]
Hi!

The runtime is not great. It depends strongly on some characteristics of the randomly generated data. Unfortunately I don't have exact runtime statistics, but when I ran 100 instantiations of the simulations, some would finish in under an hour while others can take multiple days (for example, that's why I have [a separate SLURM script to start those 29 simulation runs out of the 100, with specific random seeds, which take more than 24h](https://github.com/DIDSR/ThresholdoutAUC/blob/master/naive_data_reuse_simulation/holdout_reuse_long_jobs.srun)).

The slowest part of the simulation is the fitting of AdaBoost models (for example, <https://github.com/DIDSR/ThresholdoutAUC/blob/master/naive_data_reuse_simulation/holdout_reuse.R#L45>); that's why AdaBoost runs separately in one subprocess while the other four models run in another. Random Forest (for example, <https://github.com/DIDSR/ThresholdoutAUC/blob/master/naive_data_reuse_simulation/holdout_reuse.R#L101>) can also be very slow for some of the randomly generated datasets.

One way to try the code out while spending far less runtime is to comment out the AdaBoost and Random Forest parts (i.e., run the simulation for `glm`, `glmnet`, and SVM only), or to replace them with other classifiers that are less computationally expensive. Generally any classfier from the `caret` R package should work, since the code calls `caret` for model fitting (see [the function `fit_model_for_every_subset`](https://github.com/DIDSR/ThresholdoutAUC/blob/master/functions/fit_model_for_every_subset.R#L57)).

I hope that helps. Let me know if you have any further questions.
