### ISSUE TITLE
ROCR::prediction parameter for real data 

### ISSUE THREAD

**Issue by smilesun** [agisga/ThresholdoutAUC#4]
https://github.com/DIDSR/ThresholdoutAUC/blob/a5a3030fc53e1ab70b4e003ccc3b64cd496ec68e/functions/fit_model_for_every_subset.R#L31

for real dataset(classification task with two classes, for example, "M", "R" for the sonar dataset ), for the following lines,  the question mark filed should be one of class name if I am right? but how to choose that ? I figured out for the sonar task, it should be "R" instead of "M", since when filled up with "M" the auc is really small. 

```
pred_train <- predict(fitted_model, newdata = as.data.frame(x_train), type = "prob")
pred_train <- ROCR::prediction(predictions = pred_train[?], labels = y_train) 
```

**Comment by smilesun** [comment]
since in original code, y_train is from binomial distribution. 
`train_df$y <- factor(letters[y_train+1])`
the final y is a or b, in your original code, you choose b, so for real data, that field should by default be the second factor level?

**Comment by agisga** [comment]
Please refer to the [ROCR documentation](https://cran.r-project.org/web/packages/ROCR/ROCR.pdf) for complete clarity on this issue:

> (...) Since scoring classifiers give relative tendencies towards a negative (low scores) or positive (highscores) class, it has to be declared which class label denotes the negative, and which the positiveclass.  Ideally, labels should be supplied as ordered factor(s), the lower level corresponding to thenegative class, the upper level to the positive class.  If the labels are factors (unordered), numeric,logical or characters, ordering of the labels is inferred from R’s built-in<relation (e.g.  0 < 1, -1 <1, ’a’ < ’b’, FALSE < TRUE). (...) 

If I remember correctly, in the referenced code above, `y_train` is a 0-1-valued vector (the truth labels), and `pred_train$b` is a vector of scores denoting membership in class 1 (or equivalently, class "b"), whereas `pred_train$a` is a vector of scores denoting membership in class 0 (or equivalently, class "a"). Because the classification model is predicting membership in class 1 (equiv. "b"), I need to supply `pred_train$b` to the ROCR function.
(Some confusing may arise from the fact that class 1 is the same as class "b", and class 0 is the same as class "a". This comes from the peculiarity of the `caret` package to require that truth labels are factors rather than numeric.)
