### ISSUE TITLE
recommended ratio of n_train over n_train_total

### ISSUE THREAD

**Issue by smilesun** [agisga/ThresholdoutAUC#6]
n_train is the beginning number of instances, each round,  more instances are added until the training instance reaches n_train_total.  For real data, what could be a recommended value for n_train over of the number of training instances?

**Comment by agisga** [comment]
Sorry, I'm not sure if I understand the question. `n_train_total` is not a free parameter, it is defined as:

```
n_train_total <- n_train + n_train_increase * n_adapt_rounds
```
(for example, here: https://github.com/DIDSR/ThresholdoutAUC/blob/dd3b2bf5cd8bfc1f98fd3f6d56bf5308bfd6616a/naive_data_reuse_simulation/general_simulation.R#L7)

**Comment by smilesun** [comment]
@agisga 
sorry, to explain the question again: 
for real data, we can not control how many instances we have, we are just given the data
we want a decoupling of the problem and algorithm,  the problem is the real dataset itself(for example, the sonar dataset) and a train holdout split.   The algorithm only sees the n_train_total(so n_train_total is not **defined** in the case of real data, instead, it is **given**), what we can set  are only two parameters: n_train(the beginning number of training instances) and n_adapt_rounds.

**Comment by agisga** [comment]
Oh, I see, thanks. Right, if `n_train_total` is given, you will need to decide on `n_train`, `n_train_increase`, `n_adapt_rounds`. If the size of your (real) dataset is small that might be challenging, and you may need to keep `n_adapt_rounds` and/or `n_train_increase` small.

In the simulation study, which is given in this repository, `n_train`, `n_train_increase`, and `n_adapt_rounds` were chosen according to the goals of this computational experiment (see the paper I sent you over email), and such that the computation time is bearable with the HPC resources available to me.

However, it is hard for me to give a more specific answer to this question, because (1) neither do I know the size or composition of the (real) dataset that you are using, and (2) nor do I know what is your specific purpose to refactor this code for. Regarding (2), do you intend to use the real data to simply reproduce results similar to the ones in our paper but using real instead of simulated data? In that case, I would suggest keeping all the parameters close to their original values if possible (reduce `n_adapt_rounds` if the dataset size is too small; use computationally simpler classifiers instead of AdaBoost etc. if computation time is an issue). If the purpose is different than simply replacing simulated data with real data in the computational experiments of our paper, I would need more information to give better suggestions.
